config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'

  resources :casts
  resources :movies

  get 'movies/search' => 'movies#search'

  resources :comments

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  serialize :full_name
  attr_reader :first_name, :second_name, :last_name

  has_attached_file :avatar,
                    :styles => { :poster_size => "300x200>", :mini => "100x100" },
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar,
                                    :content_type => /\Aimage\/.*\Z/

  has_many :contracts
  has_many :movies, through: :contracts
  has_many :occupations, through: :contracts
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :cast_params, only: [:create]
  before_action :all_occupations, only: [:show]
  before_action :set_cast, only: [:show, :edit]

  def show
  end

  def edit
  end

  def index
    @casts = Cast.all
  end

  def new
    @cast = Cast.new
    @countries = Country.all
    @occupations = Occupation.all
    @movies = Movie.all
  end

  def create
    @cast = Cast.create(cast_params)
    sign_contracts(params[:cast][:occupation_ids])
  end

  def sign_contracts(occupation_ids)
    occupation_ids.reject(&:empty?).each do |occupation_id|
      Contract.find_or_create_by!(cast_id: @cast.id, occupation_id: occupation_id.to_i, movie_id: 1)
    end
  end

  private
  def set_cast
    @cast = Cast.find params[:id]
  end

  def cast_params
    params.require(:cast).permit(:born, :nationality, :occupation_ids,
                                 full_name: [:first_name, :second_name, :last_name])
  end
end

app/helpers/casts_helper.rb
module CastsHelper

  def print_name(cast)

    return "" unless cast
    cast.full_name.values.join(" ")
  end

  def print_cast_occupations(cast)
    cast.occupations.map { |e| e.title + ", " unless e.last }.uniq
  end

end

app/views/Casts/_cast.html.erb
<p class="cast frame">
  <a class="name" href="<%= cast_path(cast.id) %>"><%= print_name(cast) %></a> <br>
  Born: <%= cast.born.strftime("%e %b %Y") %> <br>
  <%= image_tag cast.avatar.url(:poster_size), align: 'left' %>
  <%= cast.biography %>
  <%= cast.nationality %>
  <br> <br> <br> <br> <br>
</p>

app/views/Casts/index.html.erb
<%= render 'users/logout' %>
<div class="main">
  <%= render @casts %>
</div>

app/views/Casts/new.html.erb
<br>
<div class="container">
<%= form_for @cast do |f| %>

    <p><%= f.fields_for :full_name do |fn| %>
          <%= fn.label :first_name %>*
          <%= fn.text_field :first_name %>*

          <%= fn.label :second_name %>
          <%= fn.text_field :second_name %>

          <%= fn.label :last_name %>
          <%= fn.text_field :last_name %>
      <% end %></p>

    <p><%= f.date_select :born,
                         use_short_month: true,
                         start_year: current_year,
                         end_year: 1900,
                         prompt: true %></p>

    <p><%= f.collection_select(:nationality, @countries, :country_name, :country_name, prompt: true) %></p>

    <p><%= f.collection_check_boxes(:occupation_ids, @occupations, :id, :title) do |o| %>
          <%= o.check_box %>
          <%= o.label %>
          <%= collection_select('cast[occupation_ids]', o.object.id.to_s, @movies, :id, :title, prompt: true) %>
          <br>
      <% end %></p>

    <%= f.submit :Save %>
<% end %>
</div>

app/views/Casts/show.html.erb
<div><%= render @cast %></div>

<!-- All Occupations -->
<% @occupations.each do |occupation| %>

    <!-- Contracts with current occupation -->
    <% contracts = @cast.contracts.where(occupation_id: occupation.id) %>
    <% unless contracts.nil? || contracts.empty? %>

        <!-- Current occupation title-->
        <div class="movies"><span class="occupation_title"><%= occupation.title %></span> <br>
          <% contracts.each do |contract| %>
              <% unless contract.movie.nil? %>

                  <!-- Movie title and link to it path -->
                  <a href="<%= movie_path(contract.movie.id) %>">

                    <!-- Avatar -->
                    <%= image_tag contract.movie.poster.url(:mini) %>
                  </a>
              <% end %>
          <% end %>
        </div>
    <% end %>
<% end %>